"""
Comprehensive CRUD tests for a PostgreSQL `songs` table.

Assumptions:
1. Table name is exactly `songs` in the current schema search path.
2. Schema includes at least:
   - id (int, primary key)
   - title (varchar/text)
   - artist (varchar/text)
   - duration_seconds (int)
3. `id` is generated by the database on INSERT (serial/identity-like behavior).
"""

import uuid

def _make_unique_song_values():
    suffix = uuid.uuid4().hex[:8]
    return f"pytest-title-{suffix}", f"pytest-artist-{suffix}", 123


def test_songs_table_exists_and_not_empty(db_cursor):
    db_cursor.execute("SELECT to_regclass('songs')")
    table_name = db_cursor.fetchone()[0]
    assert table_name == "songs", "Expected table `songs` to exist, but it was not found."

    db_cursor.execute("SELECT COUNT(*) FROM songs")
    count = db_cursor.fetchone()[0]
    assert count > 0, f"Expected `songs` to contain data, but it has {count} rows."


def test_select_returns_expected_fields_and_types(db_cursor):
    db_cursor.execute("SELECT id, title, artist, duration_seconds FROM songs LIMIT 1")
    row = db_cursor.fetchone()
    assert row is not None, "Expected at least one row from `songs`, but SELECT returned none."

    song_id, title, artist, duration_seconds = row
    assert isinstance(song_id, int), f"Expected `id` to be int, got {type(song_id).__name__}."
    assert isinstance(title, str), f"Expected `title` to be str, got {type(title).__name__}."
    assert isinstance(artist, str), f"Expected `artist` to be str, got {type(artist).__name__}."
    assert isinstance(
        duration_seconds, int
    ), f"Expected `duration_seconds` to be int, got {type(duration_seconds).__name__}."


def test_insert_song_persists(db_cursor):
    title, artist, duration_seconds = _make_unique_song_values()
    db_cursor.execute(
        """
        INSERT INTO songs (title, artist, duration_seconds)
        VALUES (%s, %s, %s)
        RETURNING id
        """,
        (title, artist, duration_seconds),
    )
    inserted_id = db_cursor.fetchone()[0]
    assert isinstance(inserted_id, int), f"Expected inserted id to be int, got {type(inserted_id).__name__}."

    db_cursor.execute(
        "SELECT title, artist, duration_seconds FROM songs WHERE id = %s",
        (inserted_id,),
    )
    inserted_row = db_cursor.fetchone()
    assert inserted_row is not None, f"Expected inserted song id={inserted_id} to exist, but it was not found."
    assert inserted_row[0] == title, f"Expected title `{title}`, got `{inserted_row[0]}`."
    assert inserted_row[1] == artist, f"Expected artist `{artist}`, got `{inserted_row[1]}`."
    assert inserted_row[2] == duration_seconds, (
        f"Expected duration_seconds `{duration_seconds}`, got `{inserted_row[2]}`."
    )


def test_update_song_persists(db_cursor):
    db_cursor.execute("SELECT id, title FROM songs LIMIT 1")
    base_row = db_cursor.fetchone()
    assert base_row is not None, "Expected at least one song to update, but table is empty."

    song_id, original_title = base_row
    updated_title = f"{original_title}-pytest-{uuid.uuid4().hex[:6]}"

    db_cursor.execute("UPDATE songs SET title = %s WHERE id = %s", (updated_title, song_id))
    assert db_cursor.rowcount == 1, f"Expected to update 1 row for id={song_id}, updated {db_cursor.rowcount}."

    db_cursor.execute("SELECT title FROM songs WHERE id = %s", (song_id,))
    refreshed_title = db_cursor.fetchone()
    assert refreshed_title is not None, f"Expected song id={song_id} to exist after update, but it was not found."
    assert refreshed_title[0] == updated_title, f"Expected updated title `{updated_title}`, got `{refreshed_title[0]}`."


def test_delete_song_removes_row(db_cursor):
    title, artist, duration_seconds = _make_unique_song_values()
    db_cursor.execute(
        """
        INSERT INTO songs (title, artist, duration_seconds)
        VALUES (%s, %s, %s)
        RETURNING id
        """,
        (title, artist, duration_seconds),
    )
    inserted_id = db_cursor.fetchone()[0]

    db_cursor.execute("DELETE FROM songs WHERE id = %s", (inserted_id,))
    assert db_cursor.rowcount == 1, f"Expected to delete 1 row for id={inserted_id}, deleted {db_cursor.rowcount}."

    db_cursor.execute("SELECT 1 FROM songs WHERE id = %s", (inserted_id,))
    exists = db_cursor.fetchone()
    assert exists is None, f"Expected song id={inserted_id} to be deleted, but it still exists."
